<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Eunhee &amp; Sangdon">
<meta name="dcterms.date" content="2024-01-19">
<meta name="description" content="Introduction to Causal Inference 강의 chapter 8 소개">

<title>PseudoLab Causal Inference Team - 09. Unobserved Confounding Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="PseudoLab Causal Inference Team">
<meta property="og:description" content="데이터 분석가가 인과추론을 공부하고 실무에 적용하면서 느낀 생각을 정리한 자료입니다.">
<meta property="og:image" content="https://github.com/CausalInferenceLab/CausalInferenceLab.github.io/posts/Introduction_to_causal_inference_Unobserved_confounding_Analysis/images/pseudo_lab_eng.png">
<meta property="og:site-name" content="PseudoLab Causal Inference Team">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../images/causal_inference_team_logo.jpg" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">PseudoLab Causal Inference Team</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">about</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://causalinferencelab.github.io/" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">09. Unobserved Confounding Analysis</h1>
                  <div>
        <div class="description">
          <p>Introduction to Causal Inference 강의 chapter 8 소개</p>
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">Unobserved Confounding Analysis</div>
                <div class="quarto-category">Sensitivity Analysis</div>
                <div class="quarto-category">Sensemakr</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Eunhee &amp; Sangdon </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">January 19, 2024</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#contents" id="toc-contents" class="nav-link active" data-scroll-target="#contents">Contents</a></li>
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#bounds" id="toc-bounds" class="nav-link" data-scroll-target="#bounds">Bounds</a>
  <ul class="collapse">
  <li><a href="#observational-counterfactual-decomposition" id="toc-observational-counterfactual-decomposition" class="nav-link" data-scroll-target="#observational-counterfactual-decomposition">Observational-Counterfactual Decomposition</a></li>
  <li><a href="#no-assumptions-bound" id="toc-no-assumptions-bound" class="nav-link" data-scroll-target="#no-assumptions-bound">[1] No-Assumptions Bound</a></li>
  <li><a href="#monotone-treatment-response-mtr" id="toc-monotone-treatment-response-mtr" class="nav-link" data-scroll-target="#monotone-treatment-response-mtr">[2] Monotone Treatment Response (MTR)</a></li>
  <li><a href="#monotone-treatment-selection-mts" id="toc-monotone-treatment-selection-mts" class="nav-link" data-scroll-target="#monotone-treatment-selection-mts">[3]Monotone Treatment Selection (MTS)</a></li>
  <li><a href="#optimal-treatment-selection-ots" id="toc-optimal-treatment-selection-ots" class="nav-link" data-scroll-target="#optimal-treatment-selection-ots">[4]Optimal Treatment Selection (OTS)</a></li>
  </ul></li>
  <li><a href="#unobserved-confounding이-과연-관측-연구에만-적용되는-이슈일까" id="toc-unobserved-confounding이-과연-관측-연구에만-적용되는-이슈일까" class="nav-link" data-scroll-target="#unobserved-confounding이-과연-관측-연구에만-적용되는-이슈일까">Unobserved Confounding이 과연 관측 연구에만 적용되는 이슈일까?</a></li>
  <li><a href="#sensitivity-analysis" id="toc-sensitivity-analysis" class="nav-link" data-scroll-target="#sensitivity-analysis">Sensitivity analysis</a>
  <ul class="collapse">
  <li><a href="#sensitivity-basiscs-in-linear-setting" id="toc-sensitivity-basiscs-in-linear-setting" class="nav-link" data-scroll-target="#sensitivity-basiscs-in-linear-setting">Sensitivity Basiscs in Linear Setting</a></li>
  <li><a href="#sensitivity-contour-plots" id="toc-sensitivity-contour-plots" class="nav-link" data-scroll-target="#sensitivity-contour-plots">Sensitivity Contour Plots</a></li>
  <li><a href="#more-general-settings" id="toc-more-general-settings" class="nav-link" data-scroll-target="#more-general-settings">More General Settings</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block page-columns page-full" id="quarto-document-content">




<p>안녕하세요, 가짜연구소 Causal Inference 팀의 최은희, 김상돈입니다.&nbsp;</p>
<p>Introduction to Causal Inference 강의의 여덟번째 챕터이며, 해당 챕터에서 다루는 내용은 아래와 같습니다.</p>
<p>강의 영상 링크 : <a href="https://youtu.be/IXNMYqUsBBQ" class="uri">https://youtu.be/IXNMYqUsBBQ</a></p>
<p>&nbsp; &nbsp; 작성된 내용 중 개선점이나 잘못된 부분이 있다면 댓글로 알려주세요!</p>
<hr>
<section id="contents" class="level2">
<h2 class="anchored" data-anchor-id="contents">Contents</h2>
<ul>
<li>&nbsp;Overview
<ul>
<li>Potential Outcomes, ATE 리마인드</li>
</ul></li>
<li>Bounds
<ul>
<li>Observational-Counterfactual Decomposition</li>
<li>No-Assumptions Bound</li>
<li>Monotone Treatment Response (MTR)</li>
<li>Monotone Treatment Selection (MTS)</li>
<li>Optimal Treatment Selection (OTS)</li>
</ul></li>
<li>Sensitivity Analysis
<ul>
<li>Linear Single Confounder</li>
<li>Towards More General Settings</li>
</ul></li>
</ul>
</section>
<section id="overview" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<ol type="1">
<li>Potential outcomes</li>
</ol>
<ul>
<li>실제 비즈니스 문제를 해결할 때 우리가 가진 Control group을 활용하여 관측되지 않은 Counterfactual(Unobserved confounders)과 최대한 같아지게 해야함</li>
<li>인과추론의 Consistency 원칙 (동일 T의 경우 그에 대한 결과도 동일해야함)Potential Outcomes
<ul>
<li>하얀 생쥐의 경우 Consist하지 않고 Counterfactual함 (이런 경우가 바로 unobserved confounding factors)</li>
</ul></li>
</ul>
<p><img src="img1.png" class="img-fluid"></p>
<p>2. ATE에 대해 다시 한번 짚어보자.</p>
<p><span class="math inline">\(\mathbb{E}[Y(1)-Y(0)]=\mathbb{E}_W[\mathbb{E}[Y\,|\, T=1,W]-\mathbb{E}[Y\,|\, T=0,W]]\)</span></p>
<ul>
<li>What is ATE(Average Treatment Effect)?
<ul>
<li>일반적으로 A/B testing에서 사용되는 분석 방법. 개인의 인과효과를 평균을 내어 집단 레벨에서 설명. 보통의 경우 교란변수(Confounders) <span class="math inline">\(W\)</span>가 관측될 경우 처치 <span class="math inline">\(T\)</span>(treatment)와 결과 <span class="math inline">\(Y\)</span>에 대한 인과를 아래와 같은 ATE 식을 기반으로 설명할 수 있음</li>
<li>위 ATE식이 성립 가능한 경우: Confounder가 모든 그룹에 동일하게 작용할때 두 그룹에 Confounding factors가 동질하게 작용하기 위해선? RCT를 통해 가능!</li>
</ul></li>
</ul>

<div class="no-row-height column-margin column-container"><div class="">
<p><img src="img2.png" class="img-fluid"></p>
</div></div><ul>
<li>하지만 ATE의 경우 Outlier에 취약한 단점 또한 있음
<ul>
<li>e.g.&nbsp;타겟군과 대조군의 매출 비교 진행 시, 만약 대조군에 타겟군의 구매액을 합친 수준의 핵과금러가 한 명이라도 존재한다면?</li>
</ul></li>
</ul>

<div class="no-row-height column-margin column-container"><div class="">
<p><img src="img3.png" class="img-fluid"></p>
</div></div><ul>
<li>Identify a point [Identification]
<ul>
<li>모든 변수가 관측가능하다고 강한 가정을 한다면, 우리는 포인트가 되는 지점을 명확히 알 수 있을 것이다.</li>
</ul></li>
</ul>
<p>3. 만약 관측 불가(Unobserved Confounders)한 <span class="math inline">\(U\)</span>를 발견하였을땐 어떡해야 할까?</p>
<ul>
<li>사실 관측 불가한 <span class="math inline">\(U\)</span>는 거의 모든 연구에서 고려해야할 사항</li>
</ul>
<p><span class="math inline">\(\begin{aligned}\mathbb{E}[Y(1)-Y(0)] &amp;=\mathbb{E}_W,_U[\mathbb{E}[Y\,|\, T=1,W,U]-\mathbb{E}[Y\,|\, T=0,W,U]] \\ &amp;\approx \mathbb{E}_W[\mathbb{E}[Y\,|\, T=1,W]-\mathbb{E}[Y\,|\, T=0,W]]\end{aligned}\)</span></p>
<ul>
<li>Identify an interval (Partial identification)
<ul>
<li>ATE를 활용하여 최대한 근사치를 찾아보자</li>
<li>한가지 가정을 내리는 것이 아닌 가정의 범위를 넓혀 [근사치], 즉 그 간격(Interval)을 추정해보자</li>
</ul></li>
</ul>

<div class="no-row-height column-margin column-container"><div class="">
<p><img src="img4.png" class="img-fluid"></p>
</div></div><blockquote class="blockquote">
<p>💡&nbsp;‘No&nbsp;Unobserved&nbsp;Confounding’&nbsp;is&nbsp;Unrealistic.<br>
&nbsp; &nbsp;현실 세계에서 모든 변수를 관측한다는 것은 불가능하다.</p>
</blockquote>
<table class="table">
<colgroup>
<col style="width: 4%">
<col style="width: 27%">
<col style="width: 52%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>1</th>
<th><strong>No-Assumptions Bound</strong></th>
<th>가정이 없다.</th>
<th>Interval 매우 김</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2</td>
<td><strong>Monotone Treatment Response</strong></td>
<td>처치(<span class="math inline">\(T\)</span>)는 언제나 결과(<span class="math inline">\(Y\)</span>)에 영향을 준다.</td>
<td>&nbsp;</td>
</tr>
<tr class="even">
<td>3</td>
<td><strong>Monotone Treatment Selection</strong></td>
<td>처치(<span class="math inline">\(T\)</span>)를 받은 군이 언제나 좋은 Potential Outcomes을 도출한다.</td>
<td>&nbsp;</td>
</tr>
<tr class="odd">
<td>4</td>
<td><strong>Optimal Treatment Selection</strong></td>
<td>개개인은 언제나 최적의 처치(<span class="math inline">\(T\)</span>)를 받는다.</td>
<td>- Interval 짧아짐</td>
</tr>
</tbody>
</table>
<p>👉 가정의 정도가 올라갈수록 현실 세계에서 발생되는 현상에 대한 설명력이 떨어진다는 한계점이 존재한다. 강한 가정 아래에서 나온 결론일수록 그 결과의 신뢰성을 떨어진다는 뜻. (“The credibility of inference decreases with the strength the assumptions maintained.” Manski)</p>
<p>👉 Interval이 짧아질수록 결과에 대한 신뢰도도 떨어질 수 있음 (개개인이 언제나 최적의 처치를 받을 확률은?)</p>
</section>
<section id="bounds" class="level2">
<h2 class="anchored" data-anchor-id="bounds">Bounds</h2>
<blockquote class="blockquote">
<p>&nbsp;💡&nbsp;지금부터&nbsp;관측이&nbsp;어려운&nbsp;변수들의&nbsp;범위를&nbsp;좁히는&nbsp;방법론들에&nbsp;대해&nbsp;알아봐보자.</p>
</blockquote>
<section id="observational-counterfactual-decomposition" class="level3">
<h3 class="anchored" data-anchor-id="observational-counterfactual-decomposition">Observational-Counterfactual Decomposition</h3>
<p>이쯤에서 다시보는 ATE. <span class="math inline">\(\mathbb{E}[Y(1)-Y(0)]=\mathbb{E}_W[\mathbb{E}[Y\,|\, T=1,W]-\mathbb{E}[Y\,|\, T=0,W]]\)</span></p>
<ul>
<li>Observational : 관측되는 부분</li>
<li>Counterfactual : 가정을 통해 범위를 좁히는 부분</li>
</ul>
<p><img src="img5.png" class="img-fluid"></p>
<blockquote class="blockquote">
<p>💡Observational-Counterfactual Decomposition<br>
<span class="math inline">\(\begin{aligned}\mathbb{E}[Y(1)-Y(0)] = \pi\mathbb{E}[Y|T=1] + (1-\pi)\mathbb{E}[Y(1)|T=0] \\ -\,\pi\mathbb{E}[Y(0)|T=1] - (1-\pi)\mathbb{E}[Y|T=0] \\ where&nbsp;\;\;&nbsp;\pi&nbsp;\triangleq&nbsp;P(T=1)\end{aligned}\)</span></p>
</blockquote>
</section>
<section id="no-assumptions-bound" class="level3">
<h3 class="anchored" data-anchor-id="no-assumptions-bound">[1] No-Assumptions Bound</h3>
<ul>
<li>가정: 범위(Bound)에 대한 가정이 없을 때 Interval Length 구해보기</li>
</ul>
<p><strong>Bounded Potential Outcomes</strong></p>
<p><span class="math inline">\(Y(0)\)</span>과 <span class="math inline">\(Y(1)\)</span>이 <span class="math inline">\(0\)</span>과 <span class="math inline">\(1\)</span> 사이에 있다고 가정했을 때 <span class="math inline">\(\mathbb{E}Y(1)-Y(0)\)</span>의 경우 음의 0과 1, 양의 0과 1 사이에 있다.</p>
<p><span class="math inline">\(-1 \le \mathbb{E}[Y(1)-Y(0)] \le 1\)</span></p>
<p>이를 일반화한다면, <span class="math inline">\(\forall t, a \le Y(t) \le b\)</span></p>
<p><span class="math display">\[ a-b \le \mathbb{E}[Y(1)-Y(0)] \le b-a \]</span></p>
<ul>
<li>Trival length limit : <span class="math inline">\(2(b-a)\)</span></li>
</ul>
<p><strong>No-Assumptions Bound</strong></p>
<ul>
<li>observational-counterfactual decomposition 와 각 방법론의 가정을 활용하여 lower bound와 upper bound를 추정하는 과정
<ul>
<li>upper bound
<ul>
<li><span class="math inline">\(\mathbb{E}[Y(1)-Y(0)] \le \pi\mathbb{E}[Y|T=1]+(1-\pi)b -\pi a-(1-\pi)\mathbb{E}[Y|T=0]\)</span></li>
</ul></li>
<li>lower bound
<ul>
<li><span class="math inline">\(\mathbb{E}[Y(1)-Y(0)] \ge \pi\mathbb{E}[Y|T=1]+(1-\pi)a -\pi b-(1-\pi)\mathbb{E}[Y|T=0]\)</span><span class="math display">\[ Interval\; Length = b-a \]</span></li>
</ul></li>
</ul></li>
<li>최초의 시작에서 범위를 반으로 줄이게 되는 것. <span class="math inline">\(2(b-a) \longrightarrow b-a\)</span></li>
<li>언제나 0을 포함한다.</li>
</ul>
<blockquote class="blockquote">
<p>💡 (앞으로 계속 나올) 예시<br>
(1) Potential outcomes 가 <span class="math inline">\(0(a)\)</span> 와 <span class="math inline">\(1(b)\)</span> 사이에 있음<br>
(2) <span class="math inline">\(\pi = 0.3\)</span> <span class="math inline">\(\mathbb{E}[Y|T=1]=0.9\)</span> <span class="math inline">\(\mathbb{E}[Y|T=0]=0.2\)</span><br>
<span class="math display">\[ -0.17 \le \mathbb{E}[Y(1)-Y(0)] \le 0.83 \]</span></p>
</blockquote>
</section>
<section id="monotone-treatment-response-mtr" class="level3">
<h3 class="anchored" data-anchor-id="monotone-treatment-response-mtr">[2] Monotone Treatment Response (MTR)</h3>
<blockquote class="blockquote">
<p>가정: 처치(T)는 언제나 결과(Y)에 영향을 준다는 가정 (Nonnegative, Nonpositive)</p>
</blockquote>
<table class="table">
<colgroup>
<col style="width: 49%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Nonnegative MTR</th>
<th>Nonpositive MTR</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\forall i\; Y_i(1) \ge Y_i(0)\)</span></td>
<td><span class="math inline">\(\forall i\; Y_i(1) \le Y_i(0)\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(0&nbsp;\le&nbsp;\mathbb{E}[Y(1)-Y(0)]&nbsp;\le&nbsp;0.83\)</span></td>
<td><span class="math inline">\(-0.17 \le \mathbb{E}[Y(1)-Y(0)] \le 0\)</span></td>
</tr>
</tbody>
</table>
<ol type="1">
<li>Nonnegative MTR (lower bound 무시)
<ul>
<li>처치는 언제나 결과에 긍정적인 영향을 준다.</li>
</ul></li>
</ol>
<p><span class="math inline">\(\forall i\; Y_i(1) \ge Y_i(0)\)</span></p>
<ul>
<li>ITE (Individual Treatment Effect) <span class="math inline">\(a - b \ge 0\)</span></li>
<li>ATE (Average Treatment Effect) <span class="math inline">\(\mathbb{E}[Y(1)-Y(0)] \ge 0\)</span></li>
</ul>
<ol type="1">
<li>Nonpositive MTR (upper bound 무시)
<ul>
<li>처치는 언제나 결과에 부정적인 영향을 준다.&nbsp;</li>
</ul></li>
</ol>
<p><span class="math inline">\(\forall i\; Y_i(1) \le Y_i(0)\)</span></p>
<ul>
<li>ITE (Individual Treatment Effect) <span class="math inline">\(a - b \le 0\)</span></li>
<li>ATE (Average Treatment Effect) <span class="math inline">\(\mathbb{E}[Y(1)-Y(0)] \le 0\)</span></li>
</ul>
</section>
<section id="monotone-treatment-selection-mts" class="level3">
<h3 class="anchored" data-anchor-id="monotone-treatment-selection-mts">[3]Monotone Treatment Selection (MTS)</h3>
<blockquote class="blockquote">
<p>가정: 처치(<span class="math inline">\(T\)</span>)를 받은 타겟군(Target)이 대조군(Control)보다 언제나 좋은 Potential Outcomes 도출한다. (MTS Upper Bound)</p>
</blockquote>
<ul>
<li><span class="math inline">\(\mathbb{E}[Y(1)|T=1] \ge \mathbb{E}[Y(1)|T=0]\)</span></li>
<li><span class="math inline">\(\mathbb{E}[Y(0)|T=1] \ge \mathbb{E}[Y(0)|T=0]\)</span></li>
</ul>
<p><span class="math display">\[ \mathbb{E}[Y(1)-Y(0)] \le \mathbb{E}[Y|T=1] - \mathbb{E}[Y|T=0] \]</span></p>
<blockquote class="blockquote">
<p>💡 그러면 이제 MTS Upper Bound에 nonnegative MTR을 합쳐보자.<br>
이를 통해 우리는 더 좁은 Interval length를 겟할 수 있다!</p>
</blockquote>
<table class="table">
<thead>
<tr class="header">
<th>No Assumptions</th>
<th><span class="math inline">\(-0.17 \le \mathbb{E}[Y(1)-Y(0)] \le 0.83\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>MTS Upper Bound</td>
<td><span class="math inline">\(-0.17 \le \mathbb{E}[Y(1)-Y(0)] \le 0.7\)</span></td>
</tr>
<tr class="even">
<td>nonnegative MTR</td>
<td><span class="math inline">\(0 \le \mathbb{E}[Y(1)-Y(0)] \le 0.83\)</span></td>
</tr>
<tr class="odd">
<td>do combine. (MTS + MTR)</td>
<td><span class="math inline">\(0 \le \mathbb{E}[Y(1)-Y(0)] \le 0.7\)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="optimal-treatment-selection-ots" class="level3">
<h3 class="anchored" data-anchor-id="optimal-treatment-selection-ots">[4]Optimal Treatment Selection (OTS)</h3>
<blockquote class="blockquote">
<p>가정: 개개인은 언제나 그들에게 최적의 처치(Optimal Treatment)를 받는다.</p>
</blockquote>
<blockquote class="blockquote">
<p>💡 OTS Assumption<br>
(1) Treatment Group (타겟군) <span class="math inline">\(T_i = 1 \Longrightarrow Y_i(1) \ge Y_i(0)\)</span><br>
(2) Nontreatment Group (대조군) <span class="math inline">\(T_i = 0 \Longrightarrow Y_i(0) &gt; Y_i(1)\)</span>&nbsp;</p>
</blockquote>
<p><strong>[4-1] 방법론1</strong></p>
<p>observational-counterfactual decomposition</p>
<ul>
<li>OTS Upper Bound 1 : <span class="math inline">\(\mathbb{E}[Y(1)|T=0] \le \mathbb{E}[Y|T=0]\)</span></li>
<li>OTS Lower Bound 2 : <span class="math inline">\(-\mathbb{E}[Y(0)|T=1] \ge -\mathbb{E}[Y|T=1]\)</span></li>
</ul>
<p><span class="math display">\[ Interval\; Length = \pi\mathbb{E}[Y|T=1]+(1-\pi)\mathbb{E}[Y|T=0]-a \]</span></p>
<table class="table">
<thead>
<tr class="header">
<th>No Assumptions</th>
<th><span class="math inline">\(-0.17 \le \mathbb{E}[Y(1)-Y(0)] \le 0.83\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>OTS Bound 1</td>
<td><span class="math inline">\(-0.14 \le \mathbb{E}[Y(1)-Y(0)] \le 0.27\)</span></td>
</tr>
</tbody>
</table>
<p>여전히 0을 포함하고 있는데…..</p>
<p><strong>[4-2] 방법론2</strong> : Bound the identifies the sign!</p>
<p>observational-counterfactual decomposition</p>
<ul>
<li>OTS Upper Bound 2 : <span class="math inline">\(\mathbb{E}[Y(1)|T=0] \le \mathbb{E}[Y|T=1]\)</span></li>
<li>OTS Lower Bound 2 : 알아서 해보래요…</li>
</ul>
<table class="table">
<thead>
<tr class="header">
<th>No Assumptions</th>
<th><span class="math inline">\(-0.17 \le \mathbb{E}[Y(1)-Y(0)] \le 0.83\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>OTS Bound 1</td>
<td><span class="math inline">\(-0.14 \le \mathbb{E}[Y(1)-Y(0)] \le 0.27\)</span></td>
</tr>
<tr class="even">
<td>OTS Bound 2</td>
<td><span class="math inline">\(0.07 \le \mathbb{E}[Y(1)-Y(0)] \le 0.76\)</span></td>
</tr>
<tr class="odd">
<td>do combine</td>
<td><span class="math inline">\(0.07 \le \mathbb{E}[Y(1)-Y(0)] \le 0.27\)</span></td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="unobserved-confounding이-과연-관측-연구에만-적용되는-이슈일까" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="unobserved-confounding이-과연-관측-연구에만-적용되는-이슈일까">Unobserved Confounding이 과연 관측 연구에만 적용되는 이슈일까?</h2>
<blockquote class="blockquote">
<p>💡 실험 연구(Experimental Study)에서 발생하는 Unobserved Confounding factors</p>
</blockquote>
<ul>
<li>관측되지 않는 교란 변수가 RCT 기반의 실험에서는 전혀 이슈가 되지 않을까?
<ul>
<li>RCT (Randomised Controlled Trial) 랜덤화 실험 (RCT 수행 목적: 그룹의 동질성)</li>
<li>우리가 원하는 이상적인 RCT 기반 A/B test는…</li>
<li>타겟군과 대조군을 랜덤하게 나누어 동질 그룹(homogeneous group)으로 분할하고, 타겟군에만 처치(Treatment)를 진행하여 나온 값에서 대조군의 값을 차감해준 결과는 처치로 인한 결과다! <span class="math inline">\(T \longrightarrow Y\)</span> (처치와 결과 사이에는 인과관계가 존재한다.)</li>
</ul></li>
</ul>

<div class="no-row-height column-margin column-container"><div class="">
<p><img src="img6.png" class="img-fluid"></p>
</div></div><ul>
<li>(특히 마케팅에서)인과추론을 잘 모르는 의사결정자의 흔한 반론. 원래 [상품/이벤트/기능개선/업데이트]가 이전보다 고객에게 매력적이어서 그런거 아냐?</li>
<li>흔한 분석가의 설명: 타겟군과 대조군 모두에게 동질하게 적용되는 외부변수임.
<ul>
<li>🤔 과연 진짜 그럴까? 의외로 날카로운 지적이었을 수도</li>
</ul></li>
</ul>

<div class="no-row-height column-margin column-container"><div class="">
<p><img src="img7.png" class="img-fluid"></p>
</div></div><ul>
<li>논문소개. (Microsoft) Common Metric Interpretation Pitfall in A/B test <a href="https://www.notion.so/Casual-Causality-efb2d821ae334b8d9674ca331edebc72">원문은 여기</a></li>
</ul>
<blockquote class="blockquote">
<p>💡 A/B test를 진행할 때 반드시 아래 4가지를 확인해야 함<br>
(1) Data Quality : 활용된 데이터가 신뢰할만한가? e.g.&nbsp;타겟군과 대조군의 동일한 모집단에서 랜덤 샘플링되었는지.<br>
(2) OverallEvaluation Criteria : 처치가 성공적이었는지, 성공했다면 어느 정도의 효과였는지, 그 효과가 통계적으로 유의한지<br>
(3) Guardrail : 실험에 영향을 주는 교란은 어느 정도였는가 (전사적으로 영향을 받으면 안되는 지표)<br>
(4) Local Feature and Diagnostic : 유저의 액션을 세밀한 수준에서 분석하여 처치의 성공 여부와 교란 변수의 영향 정도를 파악&nbsp;</p>
</blockquote>
<ul>
<li><ul>
<li>사례1. Counfounding factor - Metric Sample Ratio Mismatch(e.g.)
<ul>
<li>링크 이동 방법에 따른 유저 경험 최적화</li>
<li>링크를 새로운 탭에서 띄우는 것이 홈페이지 로드 타임을 증가시켰다 (?)</li>
</ul></li>
</ul></li>
</ul>
<table class="table">
<colgroup>
<col style="width: 7%">
<col style="width: 71%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>&nbsp;</th>
<th>가설</th>
<th>결과 (페이지 로드 수)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>타겟군</td>
<td>MSN 홈페이지에서 클릭된 어느 링크든, 새로운 탭으로 페이지가 뜬다.</td>
<td>~8.4M</td>
</tr>
<tr class="even">
<td>대조군</td>
<td>MSN 홈페이지에서 클릭된 어느 링크든, 오픈되어 있는 탭에서 링크로 이동된다.</td>
<td>~9.2M</td>
</tr>
</tbody>
</table>
<p>결론: 실험군(타겟군)에서 페이지 로드 타임이 약 8.32% 증가했다. -&gt; 기대 이상의 큰 증가</p>
<p>🌟&nbsp;<strong>Confounding factor</strong></p>
<ol type="1">
<li><p><strong>홈페이지 탭이 미리 켜져 있어 reload하지 않아도 되는 상황</strong></p></li>
<li><p><strong>대조군의 경우 브라우저에 남은 홈페이지 캐시</strong></p></li>
</ol>
<p>💡 이런 요인들을 어떻게 발견 해야할까?</p>
<ol type="1">
<li><p>비율 지표를 분해하여 어느 부분에서 차이가 발생하는지 파악</p></li>
<li><p>비율 mismatch에 영향을 받지 않는 실험군, 대조군 간의 동등하게 비교할 수 있는 subset을 찾아서 신뢰 가능한 결과를 분석</p></li>
</ol>
<ul>
<li>사례2. Counfounding factor - Novelty and Primacy Effects
<ul>
<li>(e.g.) CRM측면에서의 각 세그먼트 별 처치에 따른 효과 측정</li>
<li>그룹 A의 처치 효과가 그룹 B의 처치 효과보다 좋았다(?)</li>
</ul></li>
</ul>
<table class="table">
<colgroup>
<col style="width: 12%">
<col style="width: 43%">
<col style="width: 43%">
</colgroup>
<thead>
<tr class="header">
<th>&nbsp;</th>
<th>그룹 A</th>
<th>그룹 B</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>처치 효과</td>
<td>(처치군이 대조군에 비해) + 126% 상승</td>
<td>(처치군이 대조군에 비해) + 108% 상승</td>
</tr>
</tbody>
</table>
<p>여기서 낼 수 있는 결론: 그룹 A가 CRM 측면에서 그룹 B보다 더 좋은 세그먼트다. 그룹 A를 중심으로 한 전략을 수립해보자(?)</p>
<p><img src="img8.png" class="img-fluid"></p>
<p><img src="img9.png" class="img-fluid"></p>
<p>🌟&nbsp;<strong>Confounding factor</strong> - 그룹 A에서의 Novelty effect</p>
<ul>
<li>Novelty effect : 긍정적인 효과가 단기간 혹은 초반에만 발생하고, 기간이 길어질수록 그 효과가 나타나지 않을 때 (초두효과)</li>
<li>Primacy effect : 초반에는 유저의 반응이 극적이지 않지만, 시간이 지날수록 user learning이 발생하여 처치 최적화가 잘 이루어질때</li>
</ul>
<blockquote class="blockquote">
<p>💡 이런 요인들을 어떻게 발견 해야할까?<br>
(1) 처치 효과를 다양한 세그먼트로 쪼개어 결과를 확인해본다.<br>
(2) 처치의 효과를 일별로 쪼개어 확인해본다.<br>
(3) 실험의 기간을 늘려 장기적으로 확인해본다.</p>
</blockquote>
<ul>
<li><strong>결론</strong>
<ul>
<li>우리가 진행한 테스트 설계가 잘되어있다는 굳은 믿음에서 벗어나 결과를 주어진 리소스 안에서 최대한 비판적으로 해석해야한다.</li>
<li>A/B test를 진행할 때 발생할 수 있는 교란 변수의 범위를 정한다 하더라도 세부적인 변수들을 모두 파악하기란 힘들다. 하지만 위 논문에서 소개한대로 여러 Metric에 대해 정의를 진행하고 경험적으로 쌓인 발생 가능한 변수들에 대한 관리 시스템을 잘 구축한다면 더 발전된 추론을 할 수 있을 것이다.</li>
<li>A/B test 분석을 진행하는 분석가의 도메인에 대한 이해도, 사전 지식이 중요할 수 있다. 도메인 지식 정도에 따라 추측할 수 있는 교란 변수의 범위도 넓어질 수 있을 것이다.</li>
</ul></li>
</ul>
</section>
<section id="sensitivity-analysis" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="sensitivity-analysis">Sensitivity analysis</h2>
<p>일반적으로&nbsp;관찰&nbsp;데이터로&nbsp;인과추론&nbsp;분석을&nbsp;할&nbsp;때에는&nbsp;관측되지&nbsp;않은&nbsp;교란&nbsp;요인이&nbsp;없다는&nbsp;가정&nbsp;하에서&nbsp;분석을&nbsp;진행합니다.&nbsp;일반적으로&nbsp;이러한&nbsp;가정은&nbsp;만족될&nbsp;수&nbsp;없습니다.&nbsp;따라서&nbsp;가정이&nbsp;위반되었을&nbsp;때,&nbsp;인과&nbsp;관계에&nbsp;미치는&nbsp;영향을&nbsp;정량적으로&nbsp;확인하는&nbsp;절차,&nbsp;즉&nbsp;강건성을&nbsp;확인하는&nbsp;절차가&nbsp;필요합니다. 이것을&nbsp;측정하기&nbsp;위해&nbsp;다음과&nbsp;같은&nbsp;질문을&nbsp;해볼&nbsp;수&nbsp;있습니다.</p>
<p>관찰 데이터로 추정한 인과효과를 <span class="math inline">\(0\)</span>으로 만들기 위해서 관찰되지 않은 교란요인이 <span class="math inline">\(T\)</span>와 <span class="math inline">\(Y\)</span>에 얼마나 많은 영향을 끼쳐야 하는가? 민감도분석은 이러한 질문에 답을 하기 위한 정량적인 분석을 수행하는 것입니다.&nbsp;</p>
<section id="sensitivity-basiscs-in-linear-setting" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="sensitivity-basiscs-in-linear-setting">Sensitivity Basiscs in Linear Setting</h3>
<p>먼저&nbsp;가장&nbsp;간단한&nbsp;세팅으로&nbsp;linear&nbsp;setting을&nbsp;고려해보겠습니다.&nbsp;오른쪽&nbsp;그림을&nbsp;보면&nbsp;<span class="math inline">\(W\)</span>는&nbsp;관찰된&nbsp;교란요인이고,&nbsp;<span class="math inline">\(U\)</span>는&nbsp;관찰되지&nbsp;않은&nbsp;교란요인을&nbsp;나타냅니다.&nbsp;<span class="math inline">\(U\)</span>의&nbsp;효과를&nbsp;무시했을&nbsp;때,&nbsp;나타나는&nbsp;편향은&nbsp;어느&nbsp;정도일까요?</p>

<div class="no-row-height column-margin column-container"><div class="">
<p><img src="img10.png" class="img-fluid"></p>
</div></div><p>linear&nbsp;setting에서&nbsp;<span class="math inline">\(T\)</span>와&nbsp;<span class="math inline">\(Y\)</span>는&nbsp;다음과&nbsp;같이&nbsp;표현할&nbsp;수&nbsp;있습니다.</p>
<p><span class="math display">\[\begin{aligned} &amp;T := \alpha_w W + \alpha_u U \\ &amp;Y := \beta_w W + \beta_u U + \delta T \\ \end{aligned}\]</span></p>
<p>먼저&nbsp;<span class="math inline">\(T,&nbsp;\,&nbsp;U\)</span>가&nbsp;주어졌을&nbsp;때를&nbsp;가정하면,&nbsp;ATE는&nbsp;<span class="math inline">\(\delta\)</span>로&nbsp;계산됩니다.</p>
<p><span class="math display">\[E[Y(1) - Y(0)] = E_{W, U}[E[Y|T=1,W,U] - E[Y|T=0, W, U]] = \delta\]</span></p>
<p>하지만&nbsp;<span class="math inline">\(U\)</span>는&nbsp;관찰할&nbsp;수&nbsp;없는&nbsp;교란요인이므로,&nbsp;실제로는&nbsp;<span class="math inline">\(W\)</span>만&nbsp;조정할&nbsp;수&nbsp;있습니다.&nbsp;따라서&nbsp;<span class="math inline">\(U\)</span>의&nbsp;영향으로&nbsp;confounding&nbsp;bias가&nbsp;<span class="math inline">\(\frac{\beta_u}{\alpha_u}\)</span>&nbsp;만큼&nbsp;발생합니다.</p>
<blockquote class="blockquote">
<p><span class="math display">\[ E_W[E[Y|T=1, W]-E[Y|T=0, W]] - E_{W,U}[E[Y|T=1, W, U] - E[Y|T=0, W, U]] = \frac{\beta_u}{\alpha_u} \]</span></p>
</blockquote>
<p><span class="math inline">\(proof\)</span></p>
<p><span class="math display">\[ \begin{aligned} E_W[E[Y|T=t, W]] &amp;= E_W[E[\beta_w W + \beta_u U + \delta T|T=t, W]] \\ &amp;= E_W[\beta_w W + \beta_u E[U|T=t, W] + \delta t] \\ \newline &amp;=E_w \left[\beta_w W + \beta_u \frac{t-\alpha_w W}{\alpha_u} + \delta t\right] \\ &amp;=E_w \left[\beta_w W + \frac{\beta_u}{\alpha_u}t - \frac{\beta_u \alpha_w}{\alpha_u}W + \delta t\right] \\ &amp;=\beta_w E[W] + \frac{\beta_u}{\alpha_u}t - \frac{\beta_u \alpha_w}{\alpha_u}E[W] + \delta t \\ &amp;=\left(\delta + \frac{\beta_u}{\alpha_u}\right)t + \left(\beta_w - \frac{\beta_u \alpha_w}{\alpha_u}\right)E[W] \end{aligned} \]</span></p>
<p><span class="math display">\[ \begin{aligned} &amp;E_W[E[Y|T=1, W]-E[Y|T=0, W]] \\ &amp;= \left(\delta + \frac{\beta_u}{\alpha_u}\right)(1) + \left(\beta_w - \frac{\beta_u \alpha_w}{\alpha_u}\right)E[W] - \left[\left(\delta + \frac{\beta_u}{\alpha_u}\right)(0) + \left(\beta_w - \frac{\beta_u \alpha_w}{\alpha_u}\right)E[W]\right] \\ &amp;= \delta + \frac{\beta_u}{\alpha_u} \end{aligned}\]</span></p>
<p><span class="math display">\[ \begin{aligned} Bias &amp;= E_W[E[Y|T=1, W]-E[Y|T=0, W]] \\ &amp;- E_{W,U}[E[Y|T=1, W, U] - E[Y|T=0, W, U]] \\ &amp;= \delta + \frac{\beta_u}{\alpha_u} - \delta \\ &amp;= \frac{\beta_u}{\alpha_u} \end{aligned} \]</span></p>
</section>
<section id="sensitivity-contour-plots" class="level3">
<h3 class="anchored" data-anchor-id="sensitivity-contour-plots">Sensitivity Contour Plots</h3>
<p>true&nbsp;ATE인&nbsp;<span class="math inline">\(\delta\)</span>는&nbsp;아래와&nbsp;같이&nbsp;다시&nbsp;정리할&nbsp;수&nbsp;있습니다.</p>
<p><span class="math display">\[ E_W[E[Y|T=1, W]-E[Y|T=0, W]] = \delta + \frac{\beta_u}{\alpha_u} \]</span></p>
<p><span class="math display">\[\begin{aligned} \delta = E_W[E[Y|T=1, W]-E[Y|T=0, W]] - \frac{\beta_u}{\alpha_u} \end{aligned}\]</span></p>
<p>식을&nbsp;한번&nbsp;더&nbsp;해석해보면&nbsp;다음과&nbsp;같습니다.</p>
<ul>
<li><span class="math inline">\(U\)</span>에 의해 생기는 bias인 <span class="math inline">\(\frac{\beta_u}{\alpha_u}\)</span>이 크다면 <span class="math inline">\(E_W[E[Y|T=1, W]-E[Y|T=0, W]]\)</span>는 상쇄되고, <span class="math inline">\(\delta\)</span>는 <span class="math inline">\(0\)</span>에 가까워짐</li>
<li><span class="math inline">\(U\)</span>에 의해 생기는 bias인 <span class="math inline">\(\frac{\beta_u}{\alpha_u}\)</span>이 작다면 <span class="math inline">\(E_W[E[Y|T=1, W]-E[Y|T=0, W]]\)</span>는 크게 변화하지 않고, <span class="math inline">\(\delta\)</span>는 <span class="math inline">\(E_W[E[Y|T=1, W]-E[Y|T=0, W]]\)</span>과 큰 차이가 없음</li>
</ul>
<p>이에&nbsp;대해서&nbsp;그래프로&nbsp;나타내보면&nbsp;다음과&nbsp;같습니다.</p>
<p><img src="img11.png" class="img-fluid"></p>
<p>그림은&nbsp;(<span class="math inline">\(\frac{1}{\alpha_u}\)</span>,&nbsp;<span class="math inline">\(\beta_u\)</span>)에&nbsp;따른&nbsp;<span class="math inline">\(\delta\)</span>의&nbsp;변화&nbsp;그래프입니다.&nbsp;먼저&nbsp;green&nbsp;curve&nbsp;값을&nbsp;해석해보겠습니다.&nbsp;<span class="math inline">\(E_W[E[Y|T=1,&nbsp;W]-E[Y|T=0,&nbsp;W]]=25\)</span>로&nbsp;고정했을&nbsp;때,&nbsp;<span class="math inline">\(\frac{1}{\alpha_u}&nbsp;=&nbsp;1\)</span>이고,&nbsp;<span class="math inline">\(\beta_u&nbsp;=&nbsp;25\)</span>라면&nbsp;<span class="math inline">\(\delta&nbsp;=&nbsp;0\)</span>이&nbsp;됩니다. 따라서&nbsp;green&nbsp;curve일&nbsp;경우&nbsp;(<span class="math inline">\(\frac{1}{\alpha_u}\)</span>,&nbsp;<span class="math inline">\(\beta_u\)</span>)의&nbsp;변화에&nbsp;따른&nbsp;<span class="math inline">\(\delta&nbsp;=&nbsp;0\)</span>&nbsp;일&nbsp;때에&nbsp;해당하는&nbsp;곡선입니다.&nbsp;<span class="math inline">\(\delta&nbsp;=&nbsp;0\)</span>이라는&nbsp;의미는&nbsp;관찰되지&nbsp;않은&nbsp;교란&nbsp;요인&nbsp;<span class="math inline">\(U\)</span>에&nbsp;의해&nbsp;<span class="math inline">\(E_W[E[Y|T=1,&nbsp;W]-E[Y|T=0,&nbsp;W]]\)</span>을&nbsp;전부&nbsp;설명한다는&nbsp;의미와&nbsp;같으며,&nbsp;<span class="math inline">\(U\)</span>는&nbsp;강력한&nbsp;교란요인이라고&nbsp;볼&nbsp;수&nbsp;있습니다. 결론적으로&nbsp;green&nbsp;curve에&nbsp;가까워지거나&nbsp;혹은&nbsp;green&nbsp;curve를&nbsp;넘어설&nbsp;경우&nbsp;교란요인에&nbsp;의해&nbsp;영향을&nbsp;많이&nbsp;받으므로,&nbsp;강건성이&nbsp;떨어진다고&nbsp;볼&nbsp;수&nbsp;있습니다. 정리하면,&nbsp;관찰되지&nbsp;않은&nbsp;교란요인이&nbsp;treatment와&nbsp;outcome에&nbsp;대해&nbsp;미치는&nbsp;영향의&nbsp;방향은&nbsp;알&nbsp;수&nbsp;없습니다.&nbsp;이에&nbsp;따라&nbsp;민감도&nbsp;분석에서는&nbsp;관찰되지&nbsp;않은&nbsp;교란요인의&nbsp;**크기**를&nbsp;고려합니다.&nbsp;위의&nbsp;그림&nbsp;예시처럼&nbsp;민감도&nbsp;분석을&nbsp;통해&nbsp;추정된&nbsp;효과를&nbsp;없앨&nbsp;정도로&nbsp;추정량을&nbsp;변경하려면&nbsp;관찰되지&nbsp;않은&nbsp;교란요인의&nbsp;크기가&nbsp;어느&nbsp;정도여야&nbsp;하는지를&nbsp;확인할&nbsp;수&nbsp;있고,&nbsp;도메인&nbsp;지식을&nbsp;활용하여&nbsp;추정된&nbsp;효과의&nbsp;강건성을&nbsp;<strong>주관적</strong>으로&nbsp;결정할&nbsp;수&nbsp;있습니다.</p>
</section>
<section id="more-general-settings" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="more-general-settings">More General Settings</h3>
<p>강의에서는 더 일반적인 민감도 분석 방법에 대해 소개합니다.&nbsp;</p>
<ol type="1">
<li><p><strong>Assess-ing Sensitivity to an Unobserved Binary Covariate in an Observational Study with Binary Outcome(1983)</strong></p></li>
<li><p><strong>Making sense of sensitivity: extending omitted variable bias(2020)</strong></p></li>
</ol>
<p>이 중 두 번째 논문에 대해서 짧게 정리했습니다.&nbsp;</p>
<p>이 논문에서는 partial <span class="math inline">\(R^2\)</span>를 활용해서 linear regression에서 민감도분석을 수행하고 리포팅하기 위한 새로운 방식을 제안합니다.&nbsp;</p>
<p>**주요&nbsp;기여사항**</p>
<p>1.&nbsp;&nbsp;Robustness&nbsp;value&nbsp;개발</p>
<p>2.&nbsp;&nbsp;partial&nbsp;<span class="math inline">\(R^2\)</span>를&nbsp;활용한&nbsp;민감도분석&nbsp;툴&nbsp;개발</p>
<p>3.&nbsp;&nbsp;extreme&nbsp;scenario에&nbsp;대한&nbsp;분석&nbsp;그래프&nbsp;개발</p>
<p>해당&nbsp;논문&nbsp;저자가&nbsp;개발한&nbsp;툴은&nbsp;R,&nbsp;Python,&nbsp;Stata&nbsp;등에서&nbsp;이용할&nbsp;수&nbsp;있습니다.</p>

<div class="no-row-height column-margin column-container"><div class="">
<ul>
<li>python :&nbsp;
<ul>
<li><a href="https://github.com/nlapier2/PySensemakr">PySensemakr</a></li>
<li><a href="https://www.pywhy.org/dowhy/v0.9.1/_modules/dowhy/causal_refuters/linear_sensitivity_analyzer.html#LinearSensitivityAnalyzer.robustness_value_func">pywhy</a></li>
</ul></li>
<li>R : sensemakr&nbsp;</li>
</ul>
</div></div><p>논문에서 나오는 example이 직관적이지 않아서 다른 블로그 예시를 참고했습니다.&nbsp;</p>
<ul>
<li>참고 : <a href="https://matteocourthoud.github.io/post/ovb/" class="uri">https://matteocourthoud.github.io/post/ovb/</a></li>
<li>교육기간과 임금 사이의 관계에 관심이 있음</li>
<li>교육기간과 임금 사이에는 많은 unobserved confounder가 존재함</li>
<li>예시를 위해 unobserved confounder로 ability가 있다고 가정</li>
<li>ability는 omitted variable이지만 education과 wage에 영향을 미친다는 것을 알고 있다고 가정함</li>
</ul>

<div class="no-row-height column-margin column-container"><div class="">
<p><img src="img12.png" class="img-fluid"></p>
</div></div><pre><code>library(sensemakr)
library(tidyverse)</code></pre>
<pre><code>#setwd("./posts/2023-02-07-sensitivity-analysis")
df &lt;- read.csv("ex_data.csv")[, -1] %&gt;% 
    mutate(gender = as.factor(gender))
df %&gt;% head(2)

  age gender education wage
1  62   male         6 3800
2  44   male         8 4500</code></pre>
<pre><code>fit &lt;- lm(wage ~ ., df)
summary(fit)

Call:
lm(formula = sleep_total ~ ., data = dat)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.7435 -2.6495  0.0466  1.3376  7.0845 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 12.618464   0.862433  14.631 4.59e-11 ***
brainwt     -9.246523  14.305157  -0.646    0.527    
bodywt      -0.009216   0.013960  -0.660    0.518    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 3.476 on 17 degrees of freedom
Multiple R-squared:  0.4766,    Adjusted R-squared:  0.4151 
F-statistic: 7.741 on 2 and 17 DF,  p-value: 0.004072</code></pre>
<p>회귀분석 결과, 추정된 ATE는 약&nbsp;96으로, 교육 기간이 한 단위 증가할 때, 임금은 약 96 증가합니다(education =&nbsp;95.94). 하지만 실제로는 관찰되지 않은 교란요인(ability)이 존재하므로, 해당 추정량은 편향 추정량입니다(해당 데이터는 가상의 데이터이므로, 실제로는 수 많은 교란요인이 존재합니다).</p>
<p>관찰되지 않은 교란요인의 크기에 따라 추정된 ATE의 강건성을 분석하기 위해 민감도 분석을 수행해보겠습니다. sensemakr 패키지의&nbsp;sensemakr()&nbsp;함수를 이용해서 간단히 할 수 있습니다.</p>
<pre><code>sens &lt;- sensemakr(model = fit, treatment = "education")
summary(sens)

Sensitivity Analysis to Unobserved Confounding

Model Formula: wage ~ age + gender + education

Null hypothesis: q = 1 and reduce = TRUE 
-- This means we are considering biases that reduce the absolute value of the current estimate.
-- The null hypothesis deemed problematic is H0:tau = 0 

Unadjusted Estimates of 'education': 
  Coef. estimate: 95.9437 
  Standard Error: 38.7521 
  t-value (H0:tau = 0): 2.4758 

Sensitivity Statistics:
  Partial R2 of treatment with outcome: 0.1176 
  Robustness Value, q = 1: 0.3044 
  Robustness Value, q = 1, alpha = 0.05: 0.0627 

Verbal interpretation of sensitivity statistics:

-- Partial R2 of the treatment with the outcome: an extreme confounder (orthogonal to the covariates) that explains 100% of the residual variance of the outcome, would need to explain at least 11.76% of the residual variance of the treatment to fully account for the observed estimated effect.

-- Robustness Value, q = 1: unobserved confounders (orthogonal to the covariates) that explain more than 30.44% of the residual variance of both the treatment and the outcome are strong enough to bring the point estimate to 0 (a bias of 100% of the original estimate). Conversely, unobserved confounders that do not explain more than 30.44% of the residual variance of both the treatment and the outcome are not strong enough to bring the point estimate to 0.

-- Robustness Value, q = 1, alpha = 0.05: unobserved confounders (orthogonal to the covariates) that explain more than 6.27% of the residual variance of both the treatment and the outcome are strong enough to bring the estimate to a range where it is no longer 'statistically different' from 0 (a bias of 100% of the original estimate), at the significance level of alpha = 0.05. Conversely, unobserved confounders that do not explain more than 6.27% of the residual variance of both the treatment and the outcome are not strong enough to bring the estimate to a range where it is no longer 'statistically different' from 0, at the significance level of alpha = 0.05.</code></pre>
<p>Unadjusted Estimates of ’ education ’:는 기존 회귀분석 결과와 같습니다. Sensitivity Statistics:을 보면 partial <span class="math inline">\(R^2\)</span>와 Robustness Value(RV) 등이 표기됩니다. 또한 해당 지표에 대한 해석도 함께 제시됩니다.</p>
<ul>
<li><span class="math inline">\(RV_1\)</span>&nbsp;: 측정되지 않은 교랸요인이 교육과 임금의 잔차 변동의 30.44%를 설명한다면 추정량을 0으로 만들기 충분함 or 충분하지 않음</li>
</ul>
<p>30.44%가 충분한지 or 충분하지 않은지는 분석가의 판단에 의존합니다. 또는&nbsp;benchmark_covariates&nbsp;옵션을 통해 관찰된 <span class="math inline">\(X\)</span>&nbsp;변수와 비교함으로써 추가적인 해석을 해볼 수 있습니다.</p>
<section id="robustness-value" class="level4 page-columns page-full">
<h4 class="anchored" data-anchor-id="robustness-value">&nbsp;Robustness value&nbsp;</h4>
<p><span class="math inline">\(RV_q\)</span>는&nbsp;추정된&nbsp;treatment&nbsp;effect의&nbsp;약&nbsp;<span class="math inline">\((100&nbsp;\times&nbsp;q)\)</span>%를&nbsp;설명하기&nbsp;위해서&nbsp;unobserved&nbsp;confounder의&nbsp;효과가&nbsp;얼마나&nbsp;강력해야&nbsp;하는지를&nbsp;설명하는&nbsp;지표입니다.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p><img src="img13.png" class="img-fluid"></p>
</div></div><p><span class="math inline">\(Z&nbsp;\sim&nbsp;Y\)</span>의&nbsp;영향과&nbsp;<span class="math inline">\(Z&nbsp;\sim&nbsp;D\)</span>의&nbsp;영향이&nbsp;동일하다고&nbsp;가정할&nbsp;경우&nbsp;<span class="math inline">\(RV_q\)</span>를&nbsp;유도할&nbsp;수&nbsp;있습니다.</p>
<p><span class="math inline">\(R^2_{Y\sim&nbsp;Z|X,&nbsp;D}&nbsp;=&nbsp;R^2_{D\sim&nbsp;Z|X}=RV_q\)</span>일&nbsp;때,</p>
<p><span class="math display">\[ \begin{aligned} RV_q&nbsp;=&nbsp;\frac{1}{2}(\sqrt{f^4_q&nbsp;+&nbsp;4f^2_q&nbsp;-&nbsp;f^2_q}),&nbsp;\quad&nbsp;f&nbsp;=&nbsp;q\cdot|\frac{t}{df}|\,\,&nbsp;(cohen's\,f) \end{aligned} \]</span></p>
<ul>
<li><span class="math inline">\(RV_q \approx 1\)</span>일 경우 <span class="math inline">\(Z\)</span>가 <span class="math inline">\(Y\)</span>와 <span class="math inline">\(D\)</span>의 모든 잔차 변동을 설명한다는 것을 의미함&nbsp; &nbsp;
<ul>
<li>strong confounder</li>
</ul></li>
<li><span class="math inline">\(RV_q \approx 0\)</span>일 경우 <span class="math inline">\(Z\)</span>가 <span class="math inline">\(Y\)</span>와 <span class="math inline">\(D\)</span>의 모든 잔차 변동을 설명하지 못한다는 것을 의미함&nbsp; &nbsp; &nbsp;
<ul>
<li>weak confonder</li>
</ul></li>
</ul>
</section>
<section id="sensitivity-contour-plot" class="level4">
<h4 class="anchored" data-anchor-id="sensitivity-contour-plot">Sensitivity Contour plot&nbsp;</h4>
<p>Robustness Value는 <span class="math inline">\(R^2_{Y\sim Z|X, D} = R^2_{D\sim Z|X}\)</span>일 때를 가정하므로, <span class="math inline">\(R^2_{Y\sim Z|X, D} \neq R^2_{D\sim Z|X}\)</span>일 경우 그래프를 통해 대략적인 추이를 파악해볼 수 있습니다.&nbsp;</p>
<pre><code>plot(sens, xlab = "Partial R^2 of ability with education", 
     ylab = "Partial $R^2$ of ability with wage")</code></pre>
<p><img src="img14.png" class="img-fluid"></p>
<p>그래프를&nbsp;보면&nbsp;Unadjusted는&nbsp;관찰되지&nbsp;않은&nbsp;교란요인(ability)가&nbsp;영향을&nbsp;주지&nbsp;않을&nbsp;때를&nbsp;의미합니다.&nbsp;즉,&nbsp;회귀분석&nbsp;결과와&nbsp;동일합니다.&nbsp;우측&nbsp;상단으로&nbsp;갈수록&nbsp;관찰되지&nbsp;않은&nbsp;교란요인의&nbsp;효과가&nbsp;증가하고,&nbsp;빨간색&nbsp;dot&nbsp;line에&nbsp;도달했을&nbsp;때,&nbsp;<span class="math inline">\(\hat{\beta}_{education}&nbsp;=&nbsp;0\)</span>이&nbsp;됩니다.&nbsp;</p>
<p>그래프를&nbsp;보면&nbsp;빨간색&nbsp;dot&nbsp;line&nbsp;위에&nbsp;있는&nbsp;값으로&nbsp;<span class="math inline">\(R^2_{Y&nbsp;\sim&nbsp;Z|D,X}&nbsp;=&nbsp;0.3\)</span>,&nbsp;$&nbsp;R^2_{D&nbsp;\sim&nbsp;Z|X}&nbsp;=&nbsp;0.3$&nbsp;정도로&nbsp;생각해볼&nbsp;수&nbsp;있습니다.&nbsp;논문에서&nbsp;유도한&nbsp;공식을&nbsp;이용해서&nbsp;bias&nbsp;추정치를&nbsp;구해보고&nbsp;확인해보겠습니다.&nbsp;</p>
<p>논문에서&nbsp;partial&nbsp;<span class="math inline">\(R^2\)</span>를&nbsp;이용해서&nbsp;유도한&nbsp;bias&nbsp;추정치는&nbsp;다음과&nbsp;같습니다.&nbsp;</p>
<p><span class="math display">\[ |\hat{bias}|&nbsp;=&nbsp;\sqrt{\frac{R^2_{Y&nbsp;\sim&nbsp;Z|D,X}&nbsp;\cdot&nbsp;R^2_{D&nbsp;\sim&nbsp;Z|X}}{1&nbsp;-&nbsp;R^2_{D&nbsp;\sim&nbsp;Z|X}}}&nbsp;\cdot&nbsp;\frac{sd(Y^{\perp&nbsp;X,&nbsp;D})}{sd(D^{\perp&nbsp;X})} \]</span></p>
<pre><code>R_YZ = 0.3
R_DZ = 0.3 

DperpX &lt;- lm(education ~ age + gender, df)$residuals
YperpXD &lt;- lm(wage ~ ., df)$residuals

bias &lt;- sqrt((R_YZ*R_DZ/(1 - R_DZ)))*(sd(YperpXD)/sd(DperpX))

95.94 - bias

[1] 1.697537</code></pre>
<p><span class="math inline">\(\hat{\beta}_{education}&nbsp;=&nbsp;95.94\)</span>이고,&nbsp;<span class="math inline">\(|\hat{bias}|&nbsp;=&nbsp;94.24\)</span>이므로,&nbsp;대략&nbsp;<span class="math inline">\(0\)</span>에&nbsp;가까운&nbsp;것을&nbsp;확인할&nbsp;수&nbsp;있습니다.&nbsp;</p>
</section>
<section id="sensitivity-contour-plot-using-benchmark-covariates" class="level4">
<h4 class="anchored" data-anchor-id="sensitivity-contour-plot-using-benchmark-covariates">Sensitivity&nbsp;contour&nbsp;plot&nbsp;using&nbsp;benchmark&nbsp;covariates&nbsp;</h4>
<p>sensitivity contour plot을 봤을 때, 관찰되지 않은 교란요인의 treatment와 outcome에 미치는 영향에 따른 bias 효과를 확인해볼 수 있지만, 실제로 이 bias가 큰지 혹은 작은지는 주관적인 판단에 의존합니다. 즉, 이전 예시에서 <span class="math inline">\(R^2_{Y \sim Z|D,X} = 0.3\)</span>, <span class="math inline">\(R^2_{D \sim Z|X} = 0.3\)</span> 일 때, 추정된 회귀계수는 <span class="math inline">\(0\)</span>이 되만, <span class="math inline">\(R^2_{Y \sim Z|D,X} = 0.3\)</span>, <span class="math inline">\(R^2_{D \sim Z|X} = 0.3\)</span> 값이 큰지 혹은 작은지의 기준은 알 수 없습니다.&nbsp;</p>
<p>이러한 기준 설정의 어려움을 극복하기 위해서 관찰된 설명변수를 벤치마크하여 관찰되지 않은 교란요인이 미치는 영향의 크기를 대략적으로 추측합니다.&nbsp;</p>
<p><span class="math display">\[ \begin{aligned} k_D&nbsp;:=&nbsp;\frac{R^2_{D&nbsp;\sim&nbsp;Z|X_{-j}}}{R^2_{D&nbsp;\sim&nbsp;X_j|X_{-j}}},&nbsp;\quad k_Y&nbsp;:=&nbsp;\frac{R^2_{Y&nbsp;\sim&nbsp;Z|X_{-j},&nbsp;D}}{R^2_{Y&nbsp;\sim&nbsp;X_j|X_{-j},&nbsp;D}} \end{aligned} \]</span></p>
<p><span class="math inline">\(k_D \ge 1\)</span>일 때, <span class="math inline">\(R^2_{D \sim Z|X_{-j}} \ge R^2_{D \sim X_j|X_{-j}}\)</span>이므로 관찰되지 않은 교란요인이 사전에 지정한 설명변수 대비 Treatment에 미치는 영향이 크다는 의미로 볼 수 있습니다. <span class="math inline">\(k_Y \ge 1\)</span>일 때도 마찬가지로 관찰되지 않은 교란요인이 사전에 지정한 설명변수 대비 반응변수에 미치는 영향이 크다는 의미로 볼 수 있습니다.</p>
<pre><code>sens2 &lt;- sensemakr(model = fit, treatment = "education", 
                  benchmark_covariates = "age", 
                  kd = c(0.5, 1, 2), 
                  ky = c(0.5, 1, 2))

plot(sens2)</code></pre>
<p><img src="img15.png" class="img-fluid"></p>
<p>sensemakr()&nbsp;함수에는&nbsp;`benchmark_covariates`&nbsp;옵션이&nbsp;존재하며,&nbsp;<span class="math inline">\(k_D\)</span>,&nbsp;<span class="math inline">\(k_Y\)</span>의&nbsp;크기를&nbsp;사전에&nbsp;지정할&nbsp;수&nbsp;있습니다.&nbsp;그래프를&nbsp;해석해보면&nbsp;관찰되지&nbsp;않은&nbsp;교란요인(ability)가&nbsp;age의&nbsp;두&nbsp;배&nbsp;정도의&nbsp;설명력을&nbsp;갖더라도,&nbsp;<span class="math inline">\(\hat{\beta}_{education}&nbsp;=&nbsp;67.61\)</span>로&nbsp;값의&nbsp;변화는&nbsp;있지만&nbsp;부호는&nbsp;여전히&nbsp;positive인&nbsp;것을&nbsp;볼&nbsp;수&nbsp;있습니다.&nbsp;</p>
<p>옵션을&nbsp;추가할&nbsp;경우&nbsp;해당&nbsp;plot에서&nbsp;통계적&nbsp;유의성&nbsp;또한&nbsp;체크해볼&nbsp;수&nbsp;있습니다.&nbsp;</p>
<pre><code>plot(sens2, sensitivity.of = "t-value")</code></pre>
<p><img src="img16.png" class="img-fluid"></p>
<p>통계적 유의성을 보면 관찰되지 않은 교란요인(ability)가 <span class="math inline">\(1 \times age\)</span>보다 약간 큰 정도의 설명력을 갖는다면, <span class="math inline">\(\hat{\beta}_{education}\)</span>이 통계적으로 유의하지 않게 바뀔 수 있다는 것을 의미합니다.&nbsp;</p>
<pre><code>plot(sens2)
add_bound_to_contour(r2dz.x = 0.3, 
                     r2yz.dx = 0.3, 
                     bound_label = "Something related to\nboth outcome and treatment")</code></pre>
<p><img src="img17.png" class="img-fluid"></p>
<p>추가적으로&nbsp;임의로&nbsp;partial&nbsp;<span class="math inline">\(R^2\)</span>를&nbsp;설정해서&nbsp;점을&nbsp;찍어볼&nbsp;수도&nbsp;있습니다.&nbsp;</p>
</section>
<section id="sensitivity-plots-of-extreme-scenarios" class="level4">
<h4 class="anchored" data-anchor-id="sensitivity-plots-of-extreme-scenarios">Sensitivity&nbsp;plots&nbsp;of&nbsp;extreme&nbsp;scenarios</h4>
<p>extreme&nbsp;scenario는&nbsp;outcome의&nbsp;거의&nbsp;모든&nbsp;잔차&nbsp;변동을&nbsp;관찰되지&nbsp;않은&nbsp;교란요인이&nbsp;설명한다는&nbsp;의미로,&nbsp;<span class="math inline">\(R_{Y&nbsp;\sim&nbsp;Z|D,X}&nbsp;=&nbsp;1\)</span>을&nbsp;의미합니다(옵션으로&nbsp;<span class="math inline">\(0.75,&nbsp;0.5\)</span>일&nbsp;때도&nbsp;함께&nbsp;제시됨).&nbsp;그래프를&nbsp;활용하여&nbsp;extreme&nbsp;scenario일&nbsp;때,&nbsp;<span class="math inline">\(R^2_{D&nbsp;\sim&nbsp;Z|X}\)</span>의&nbsp;변화에&nbsp;따라&nbsp;추정된&nbsp;회귀계수가&nbsp;어떻게&nbsp;바뀌는지를&nbsp;시각화해볼&nbsp;수&nbsp;있습니다.&nbsp;</p>
<pre><code>sens3 &lt;- sensemakr(model = fit, treatment = "education", 
                  benchmark_covariates = "age", 
                  kd = c(1, 2, 3, 4), 
                  ky = c(1, 2, 3, 4))
plot(sens3, type = "extreme", lim = 0.5)
result &lt;- plot(sens3, type = "extreme", lim = 0.5)</code></pre>
<p><img src="img18.png" class="img-fluid"></p>
<pre><code>result$scenario_r2yz.dx_1[117:119,]

    r2dz.x r2yz.dx adjusted_estimate
117  0.116       1         0.7348541
118  0.117       1         0.2712232
119  0.118       1        -0.1912156</code></pre>
<ul>
<li>&nbsp;x axis : <span class="math inline">\(R^2_{D \sim Z|X}\)</span>&nbsp;</li>
<li>y axis : <span class="math inline">\(\hat{\tau} = \hat{\tau}_{res} - \hat{bias}\)</span>&nbsp;</li>
<li>line : <span class="math inline">\(R^2_{Y \sim Z|D,X}\)</span></li>
</ul>
<p>그래프를&nbsp;보면&nbsp;빨간색&nbsp;dot&nbsp;line은&nbsp;추정된&nbsp;회귀계수가&nbsp;0이&nbsp;되는&nbsp;경우에&nbsp;해당합니다.&nbsp;solid&nbsp;line은&nbsp;<span class="math inline">\(R^2_{Y&nbsp;\sim&nbsp;Z|D,X}&nbsp;=&nbsp;1\)</span>일&nbsp;때에&nbsp;해당합니다.&nbsp;<span class="math inline">\(R^2_{Y&nbsp;\sim&nbsp;Z|D,X}&nbsp;=&nbsp;1\)</span>일&nbsp;때,&nbsp;추정된&nbsp;회귀계수가&nbsp;0이&nbsp;되기&nbsp;위해서는&nbsp;<span class="math inline">\(R^2_{D&nbsp;\sim&nbsp;Z|X}&nbsp;\approx&nbsp;0.117\)</span>&nbsp;정도&nbsp;되어야&nbsp;하는&nbsp;것을&nbsp;확인할&nbsp;수&nbsp;있습니다.&nbsp;&nbsp;</p>
<p>또한, 왼쪽 하단에 빨간색 vertical line은 benchmark로 설정한 변수에 비해 confounder가 몇 배 더 강력한지를 나타내는 것으로 `kd = c(0.5, 1, 2)` 옵션에서 설정한 것과 같습니다.&nbsp;</p>
<p>관찰된 설명변수 age가 education에 미치는 효과에 비해서 관찰되지 않은 교란요인이 education에 미치는 효과가 네 배 정도 클 때, <span class="math inline">\(\hat{\beta}_{education} \approx 0\)</span>이 되는 것을 확인할 수 있습니다.&nbsp;</p>
<p>상식적으로&nbsp;교육기간과&nbsp;나이는&nbsp;충분한&nbsp;양의&nbsp;상관관계가&nbsp;존재한다고&nbsp;생각할&nbsp;수&nbsp;있습니다.&nbsp;따라서&nbsp;관찰된&nbsp;설명변수&nbsp;age가&nbsp;education에&nbsp;미치는&nbsp;효과에&nbsp;비해서&nbsp;관찰되지&nbsp;않은&nbsp;교란요인이&nbsp;education에&nbsp;미치는&nbsp;효과가&nbsp;네&nbsp;배정도&nbsp;클&nbsp;때,&nbsp;<span class="math inline">\(\hat{\beta}_{education}&nbsp;\approx&nbsp;0\)</span>이&nbsp;된다는&nbsp;의미는&nbsp;ATE&nbsp;추정량이&nbsp;충분히&nbsp;신뢰할&nbsp;수&nbsp;있고,&nbsp;관찰되지&nbsp;않은&nbsp;교란요인에&nbsp;강건하다는&nbsp;것을&nbsp;의미한다고&nbsp;볼&nbsp;수&nbsp;있습니다(<strong>주관적인 해석</strong>).&nbsp;&nbsp;</p>
</section>
<section id="pywhy-tutorial" class="level4">
<h4 class="anchored" data-anchor-id="pywhy-tutorial">pywhy tutorial&nbsp;</h4>
<pre><code>import dowhy
from dowhy import CausalModel
import pandas as pd
import numpy as np
import dowhy.datasets
import os
from dowhy import CausalModel</code></pre>
<pre><code>dat = pd.read_csv("posts/2023-02-07-sensitivity-analysis/ex_data.csv", index_col = 0)
dat.head()</code></pre>
<pre><code>gdot = """graph[directed 1 node[id "age" label "age"]
                    node[id "gender" label "gender"]
                    node[id "education" label "education"]
                    node[id "wage" label "wage"]
                    
                    edge[source "education" target "wage"]
                    edge[source "gender" target "wage"]
                    edge[source "age" target "wage"]]"""</code></pre>
<pre><code>model = CausalModel(
            data = dat,
            treatment="education",
            outcome="wage", 
            graph = gdot
        )</code></pre>
<pre><code>identified_estimand = model.identify_effect(proceed_when_unidentifiable=True)
print(identified_estimand)</code></pre>
<pre><code>estimate = model.estimate_effect(identified_estimand,
                                 method_name="backdoor.linear_regression")</code></pre>
<pre><code>refute = model.refute_estimate(identified_estimand, 
                               estimate,
                               method_name = "add_unobserved_common_cause",
                               simulated_method_name = "linear-partial-R2",
                               benchmark_common_causes = "age",
                               effect_fraction_on_treatment = [ 1,2,3]
                              )</code></pre>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>