project:
  type: website
  
website:
  comments:
      utterances:
        repo: quarto-dev/quarto-docs
        theme: dark-blue
  title: "가짜연구소 인과추론팀 Blog"
  description: "가짜연구소 인과추론팀의 인과추론 블로그입니다."
  search: true
  navbar:
    logo: images/causal_inference_team_logo.jpg
    right:
      - about.qmd
      - icon: github
        href: https://causalinferencelab.github.io/
  open-graph: 
    title: "가짜연구소 인과추론팀 Blog"
    description: "가짜연구소 인과추론팀의 인과추론 블로그입니다."
    image: images/pseudo_lab_eng.png        
        
format:
  html:
    theme:
        light: [cosmo, theme.scss, anari-custom.scss]
        dark: [cosmo, theme-dark.scss, anari-custom.scss]
    css: styles.css
    
execute: 
  warning: false
  freeze: auto

editor: visual